---
title: Case Study Gruppe 11
author: Ida Kossatz
date: '2024-02-23'
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
      smooth_scroll: false
    number_sections: true
    theme: spacelab
    highlight: espresso
      
---
```{r setup, include=FALSE}
# install.packages("yaml")

library(yaml)
```
# Vorbereiten der Programmierumgebung
Um alle gewünschten Imports, Operationen und Anpassungen vornehmen zu können., wird das Tidyverse Package installiert und die Packages readr, dplyr, tidyr und stringr geladen.

```
install.packages("tidyverse")
library(readr)
library(dplyr) 
library(tidyr) 
library(stringr)
```


# Importieren der Daten
Um die Case Study bearbeiten zu können wurden folgende Datensätze wurden importiert.
Dabei sind die Einzeldateien zugehörig zu ihren jeweiligen Komponenten aufgelistet. Sollten Daten aus den Einzelteile Tabellen für unterschiedliche Komponenten genutzt werden, so werden diese einmal beim ersten Aufruf importiert.
Da für die Aufgabe Einzelteile und Komponenten aus dem Fahrzeug Typ 11 gebraucht werden, welches von der Firma OEM1 gebaut wird, werden anhand der ersten drei Tabellen die restlichen benötigten Dateien rausgesucht.

- Fahrzeuge_OEM1_Typ11
- Bestandteile_Fahrzeuge_OEM1_Typ11
- Fahrzeuge_OEM1_Typ11_Fehleranalyse
- Komponente_K1BE1
  - Einzelteil_T01
  - Einzelteil_T02
  - Einzelteil_T03
  - Einzelteil_T04
- Komponente_K1DI1
  - Einzelteil_T05
  - Einzelteil_T06
- Komponente_K2LE1
  - Einzelteil_T11
  - Einzelteil_T14
  - Einzelteil_T15
- Komponente_K2ST1
  - Einzelteil_T12
  - Einzelteil_T13
- Komponente_K3AG1
  - Einzelteil_T21
  - Einzelteil_T24
  - Einzelteil_T25
- Komponente_K3SG1
  - Einzelteil_T22
  - Einzelteil_T23
- Komponente_K4
  - Einzelteil_T30
  - Einzelteil_T31
  - Einzelteil_T32

Anhand folgender Beispiele wurden oben genannte Dateien importiert.


## Import Funktionen für unterschiedliche Dateitypen {.tabset}
Die unterschiedlichen Importbefehle werden jeweils anhand von Beispielen aus dem Originalcode gezeigt.

### .csv
CSV Dateien bei welcher die Spalten mit einem Komma separiert sind werden wie folgt importiert. In diesem Fall wird die Datei Fahrzeuge OEM Typ 11 als Beispiel genutzt.
```
Fahrzeuge_OEM1_Typ11 <- read_csv(".\\Data\\Fahrzeug\\Fahrzeuge_OEM1_Typ11.csv")
```

CSV Dateien bei welcher die Spalten dagegen mit einem Semikolon separiert sind werden mit folgendem
Befehl importiert. Hier wird die Tabelle Bestandteile Fahrzeuge OEM1 Typ11 als Beispiel genutzt.
```
Bestandteile_Fahrzeuge_OEM1_Typ11 <- read_csv2(".\\Data\\Fahrzeug
                                                 \\Bestandteile_Fahrzeuge_OEM1_Typ11.csv ")
```

### .txt einzeilig
Einzeilige Text (.txt) Dateien werden zuerst als String eingelesen. Anschließend werden die Spalten Delimiter mit `\t` ersetzt und die Zeilen Delimiter mit `\n`.
```
Einzelteil_T01_str <- readLines(paste(".\\Data\\Einzelteil\\Einzelteil_T01.txt"), warn=FALSE)
Einzelteil_T01_str <- str_replace_all(Einzelteil_T01_str, "[|]", "")
Einzelteil_T01_str <- str_replace_all(Einzelteil_T01_str, "[[:space:]]{3}", "\t")
Einzelteil_T01_str <- str_replace_all(Einzelteil_T01_str, " \"", "\n\"")

```
Die Funktion  mit der mehrzeilige .txt Dateien eingelesen werden können, braucht eine Datei als Input. Deswegen wird der eingelesene und angepasste String in eine temporäre Datei gespeichert. Um im weiteren Verlauf Tabellen mit gleichen Spaltennamen zu erhalten, werden die Spaltennamen im read_delim() Befehl mit festgelegt.
```
tf <- tempfile()
writeLines(Einzelteil_T01_str, tf)
Einzelteil_T01 <- read_delim(tf, col_names = c("ID", "X1", "ID_T1", "Produktionsdatum", 
                  "Herstellernummer", "Werksnummer", "Fehlerhaft", "Fehlerhaft_Datum", 
                  "Fehlerhaft_Fahrleistung"), skip = 1)
```                                               
Um Arbeitsspeicher zu sparen werden der eingelesene String und die temporäre Datei wieder gelöscht. Die brauchbare Tabelle wurde im vorhergehenden Schritt als Variable gespeichert.
```
rm(Einzelteil_T01_str, tf)
```

### .txt mehrzeilig
Da R bei mehrzeiligen .txt Dateien den Zeilenumbruch erkennt, muss nur der Spaltenumbruch festgelegt werden. Auch hier werden die Spaltennamen für einheitliches Arbeiten  eigenständig festgelegt.

```
Komponente_K2ST1 <- read_delim(".\\Data\\Komponente\\Komponente_K2ST1.txt", delim="|",
                               col_names = c("ID", "X1", "ID_Sitze", "Produktionsdatum", 
                               "Herstellernummer", "Werksnummer", "Fehlerhaft", 
                               "Fehlerhaft_Datum", "Fehlerhaft_Fahrleistung"), skip = 1)

```

# Datenaufbereitung

## Anpassung und Verbinden von Tabellen
Da abschließend eine Tabelle mit allen benötigten Daten erstellt werden soll, müssen die benötigten Tabellen sortiert, gereinigt und miteinander verbunden werden.
Diese Befehle werden für so gut wie jede Tabelle genutzt, deshalb bietet es sich an dies durch Funktionen zu definieren, welche dann nur noch aufgerufen werden müssen.
Dabei werden innerhalb der Funktion auch einzelne Spalten manipuliert und fehlerhafte Daten aussortiert um anschließend einen sortierten Datensatz zu erhalten.
Die finale Tabelle soll aus allen benötigten Komponenten und Einzelteilen folgende Spalten beinhalten:

- Fehlerhafte Fahrleistung
- Betriebsdauer
- Herstellernummer
- ID Self
- ID Parent
- Lieferdauer
- Produktionsdatum

ID-Self beinhaltet dabei die ID des Einzelteils oder der Komponente und ID-Parent beschreibt die bei Einzelteilen die ID der dazugehörigen Komponente, sowie bei Komponenten die dazugehörigen ID des Fahrzeugs. Es wäre möglich diese zwei Attribute in eine Spalte mit eine Namen wie z.B. ID einzusortieren, da jeweils nur die Komponenten ID wirklich relevante ist, jedoch ist es übersichtlicher und leichter verständlich wenn beide Attribute in separaten Spalten beibehalten werden.


### Funktionen zum Verbinden von Tabellen {.tabset}

#### "Transform" Funktion für Komponenten
Diese Funktion verbindet die Komponenten mit den Fahrzeugdaten dabei werden die benötigen Parameter extrahiert.
Das Argument "Join" ist ein String, da für die unterschiedlichen Komponenten wie z.B. Motoren oder Schaltungen, die Tabellen anhand von verschiedenen ID'S verbunden werden müssen.
Die Funktion filtert die Komponenten Datei nach Einträgen in der Fehlerhaft_Datum Spalte, da nur diese relevant für die Aufgabenstellung sind. Anschließend wird die Komponenten Datei mit der Fahrzeuge_OEM1_Typ11 Datei verbunden, dabei werden fehlerhafte Einträge aussortiert. Um die benötigte Angabe Lieferdauer zu erstellen werden für jeden Zeileneintrag das Produktionsdatum des Fahrzeuges abgezogen dem Produktionsdatum der Komponente berechnet und als Spalte mit dem Namen Lieferdauer der Tabelle hinzugefügt.
Danach werden die final benötigten Spalten selektiert und namentlich gegebenenfalls angepasst um eine einheitliche Namensgebung zu gewährleisten.

```
Komponente_Transform <- function (Komponente, Join = ""){
  Komponente <- Komponente %>%
    filter(!is.na(Fehlerhaft_Datum)) %>%
    left_join(Fahrzeuge_OEM1_Typ11, by = Join) %>%
    drop_na() %>%
    mutate(Lieferdauer = Produktionsdatum.y - Produktionsdatum.x) %>%
    select(c(Fehlerhaft_Fahrleistung = Fehlerhaft_Fahrleistung, Betriebsdauer, 
             Herstellernummer, ID_Self = matches(Join) , ID_Parent = ID_Fahrzeug, 
             Lieferdauer, Produktionsdatum = Produktionsdatum.x))
}
```

#### "Transform" Funktion für Einzelteile
Diese Funktion verbindet die Einzelteile mit den Komponenten, dabei werden die benötigen Parameter extrahiert.
Das Argument "Join" ist auch hier ein String, da die ID für jedes Einzelteil anders ist.
Zuerst werden die beiden Tabellen verknüpft, dabei werden fehlerhafte Einträge aussortiert. Um die benötigte Angabe Lieferdauer zu erstellen werden für jeden Zeileneintrag das Produktionsdatum der Komponente abgezogen dem Produktionsdatum des Einzelteils berechnet und als Spalte mit dem Namen Lieferdauer der Tabelle hinzugefügt.
Danach werden die final benötigten Spalten selektiert und namentlich gegebenenfalls angepasst um eine einheitliche Namensgebung zu gewährleisten.

```
Einzelteil_Transform <- function(Teil, Komponente, Join = ""){
  Teil <- Teil %>%
    left_join(Komponente, by=Join) %>%
    drop_na() %>%
    mutate(Lieferdauer = Produktionsdatum.y - Produktionsdatum.x) %>%
    select(c(Fehlerhaft_Fahrleistung = Fehlerhaft_Fahrleistung.x, Betriebsdauer, 
             Herstellernummer = Herstellernummer.x, ID_Self = matches(Join), 
             ID_Parent = ID_Self, Lieferdauer, Produktionsdatum = Produktionsdatum.x))
}
```

## Importieren, Anpassen und Speichern der Einzelteile und der Komponenten (Teil 1)
Zunächst wird der Ablauf beschreiben, welcher den Import, das Anpassen mit den oben beschriebenen Funktionen und das finale Speichern als Variable durchführt. Dies ist für jede Komponente annähernd identisch und wird deshalb nur anhand einer Komponente beispielhaft beschrieben. In diesem Fall Komponente K1BE1.

1. Einlesen der Datei mit Hilfe der oben beschriebenen [Import Funktionen für unterschiedliche Dateitypen] .

```
Komponente_K1BE1 <- read_csv(".\\Data\\Komponente\\Komponente_K1BE1.csv")
```

2. Gegebenenfalls Anpassen der Tabelle, so dass alle Spalten den gleichen Namen tragen und den richtigen Dateityp haben. Das ist wichtig, damit die "Transform" Funktionen funktionieren.
```
Komponente_K1BE1 <- Komponente_K1BE1 %>%
  mutate(Produktionsdatum = as.Date(Produktionsdatum_Origin_01011970)) %>%
  select(c(Fehlerhaft_Fahrleistung, Fehlerhaft_Datum, Herstellernummer, ID_Motor, Produktionsdatum))
```

3. Die "[Transform" Funktion für Komponenten] wird aufgerufen, mit den dazugehörigen Argumenten.
```
Komponente_K1BE1 <- Komponente_Transform(Komponente_K1BE1, "ID_Motor")
```

4. Einlesen der passenden Tabelle, welche die Bestandteile der Komponente beinhaltet.

```
Bestandteile_Komponente_K1BE1 <- read_csv2(".\\Data\\Komponente\\Bestandteile_Komponente_K1BE1.csv")
```

5. Zusammenfügen der Komponenten Tabelle mit der Bestandteile der Komponente Tabelle, um die Einzelteile zuordnen zu können.
```
Komponente_K1BE1 <- Komponente_K1BE1 %>%
  left_join(Bestandteile_Komponente_K1BE1, by=join_by("ID_Self" == ID_K1BE1))
```

6. Einlesen der Einzelteildateien, welche in diesem Beispiel eine .txt Datei ist. Dieser Vorgang wird in Abschnitt "[Importbefehle für unterschiedliche Dateitypen]" ausführlich beschrieben. Hinzu kommt hier nur noch das Zwischenspeichern der Datei, da diese auch für eine andere Komponente benötigt wird und so das doppelte importieren vermieden wird.
In diesem Beispiel wird für eine Komponente nur ein Einzelteil eingelesen. Welche Einzelteile für welche Komponenten benötigt werden ist aus der Auflistung im Abschnitt "[Importieren der Daten]" zu entnehmen. In dem Fall von mehreren Einzelteil pro Komponente erfolgt das Importieren und Einbinden analog. 
```
Einzelteil_T01_str <- readLines(paste(".\\Data\\Einzelteil\\Einzelteil_T01.txt"), warn=FALSE)
Einzelteil_T01_str <- str_replace_all(Einzelteil_T01_str, "[|]", "")
Einzelteil_T01_str <- str_replace_all(Einzelteil_T01_str, "[[:space:]]{3}", "\t")
Einzelteil_T01_str <- str_replace_all(Einzelteil_T01_str, " \"", "\n\"")

tf <- tempfile()
writeLines(Einzelteil_T01_str, tf)
Einzelteil_T01 <- read_delim(tf, col_names = c("ID", "X1", "ID_T1", "Produktionsdatum", 
                                               "Herstellernummer", "Werksnummer",
                                               "Fehlerhaft", "Fehlerhaft_Datum", 
                                               "Fehlerhaft_Fahrleistung"), skip = 1)

rm(Einzelteil_T01_str, tf)

Einzelteil_T01_K1DI1 <- Einzelteil_T01
```

7. Die benötigten Spalten aus der Einzelteiltabelle auswählen und falls im Schritt 6 noch nicht geschehen, die Spaltennamen anpassen an die vorab festgelegten Namen. 
```
Einzelteil_T01 <- Einzelteil_T01 %>%
  select(c(Fehlerhaft_Fahrleistung, Herstellernummer, ID_T1, Produktionsdatum))
  
```

8. Die ["Transform" Funktion für Einzelteile] wird aufgerufen, mit den dazugehörigen Argumenten.
```
Einzelteil_T01 <- Einzelteil_Transform(Einzelteil_T01, Komponente_K1BE1, "ID_T1")
```

9. Die Schritte 6 bis 8 für alle benötigten Einzelteile der Komponente wiederholen, in diesem Fall beispielhaft für Einzelteil T04.
```
Einzelteil_T04 <- read_csv2(".\\Data\\Einzelteil\\Einzelteil_T04.csv")

Einzelteil_T04 <- Einzelteil_T04 %>%
  mutate(Produktionsdatum = as.Date(Produktionsdatum_Origin_01011970)) %>%
  select(c(Fehlerhaft_Fahrleistung, Herstellernummer, ID_T4 = ID_T04, Produktionsdatum))
  
Einzelteil_T04 <- Einzelteil_Transform(Einzelteil_T04, Komponente_K1BE1, "ID_T4")
```

# Erstellen des finalen Datensatzes

## Importieren, Anpassen und Speichern der Einzelteile und der Komponenten (Teil 2)
In diesem Abschnitt wird beschrieben wie die Tabellen für Einzelteile und Komponenten in der finalen Tabelle zusammengefügt werden.

10. Zusammenfügen aller Einzelteile in die Tabelle der Komponente. Dabei werden nur die Spalten ausgewählt welche für den weiteren Verlauf wichtig sind. Somit werden die Spalten weggelassen welche nur für das Verknüpfen der Tabellen relevant waren. Die Funktion bind_rows() fügt dabei die Tabellen übereinander ein.
```
Komponente_K1BE1 <- Komponente_K1BE1 %>%
  select(c(Fehlerhaft_Fahrleistung, Betriebsdauer, Herstellernummer, ID_Self, 
           ID_Parent, Lieferdauer, Produktionsdatum)) %>%
  bind_rows(list(Einzelteil_T01, Einzelteil_T02, Einzelteil_T03, Einzelteil_T04))
```

11. Danach werden alle ursprünglichen Dateien gelöscht welche jetzt sortiert und aufgearbeitet in der finalen Tabelle als Kopie vorhanden sind. Um Arbeitsspeicher einzusparen und da diese nicht mehr benötigt werden.
```
rm(Einzelteil_T01, Einzelteil_T02, Einzelteil_T03, Einzelteil_T04, Bestandteile_Komponente_K1BE1)
```

12. Abschließend wird Schritt 1 bis 11 für alle Komponenten und Einzelteile aus der Auflistung im Abschnitt "[Importieren der Daten]" wiederholt.

# Für Vera und Minh
Folgende Gliederungspunkte sollen im Inhaltsverzeichnis mindestens aufgeführt werden:

# Auswertung

# Ergebnis